# Auto-Channel configuration file

# Desired Resolution
W = 854 
H = 480

MAX_SAME_FILE_RETRIES = 3  # Number of times to attempt playing a file before giving up
MAX_CONSECUTIVE_RETRIES = 3  # If several consecutive files fail, exit program

PLAYOUT_FILE = 'playout.ini'
OUTPUT_LOCATION = 'rtmp://localhost/live/stream'
LOOP = True

SCHEDULER_UPNEXT_VIDEO_FOLDER = 'upnext/video'
SCHEDULER_UPNEXT_AUDIO_FOLDER = 'upnext/audio'
SCHEDULER_UPNEXT_WISDOM_FILE = 'upnext/wisdom.txt'

BUMP_FOLDER = 'bumpers'

OVERLAY_FILE = 'upnext/comfychan.png'
OVERLAY_FILE_OUTLINE = 'upnext/comfychanline.png'
OVERLAY_X = W - 120
OVERLAY_Y = 0

SERV_DRAWTEXT_X = 25
SERV_DRAWTEXT_Y = 25
SERV_DRAWTEXT_SHADOW_X = 2
SERV_DRAWTEXT_SHADOW_Y = 2
SERV_DRAWTEXT_SHADOW_COLOR = 'black'
SERV_DRAWTEXT_FONT_FILE = 'fonts/hc-too5.ttf'
SERV_DRAWTEXT_FONT_SIZE = 20
SERV_DRAWTEXT_FONT_COLOR = 'white'
SERV_OUTPUT_ACODEC = 'aac'

SERV_OUTPUT_ASPECT = "%s:%s" % (W, H)
SERV_OUTPUT_CRF = 18
SERV_OUTPUT_PRESET = 'slow'

CLIENT_VIDEO_SCALE = "%sx%s" % (W, H)

CLIENT_DRAWTEXT_X = 25
CLIENT_DRAWTEXT_Y = 90
CLIENT_DRAWTEXT_SHADOW_X = 2
CLIENT_DRAWTEXT_SHADOW_Y = 2
CLIENT_DRAWTEXT_SHADOW_COLOR = 'black'
CLIENT_DRAWTEXT_FONT_FILE = 'fonts/hc-too5.ttf'
CLIENT_DRAWTEXT_FONT_SIZE = 18
CLIENT_DRAWTEXT_FONT_COLOR = 'white'

CLIENT_VCODEC = 'h264'
CLIENT_ASPECT = "%s:%s" % (W, H)
CLIENT_FLAGS = '+cgop'
CLIENT_G = 120
CLIENT_ACODEC = 'aac'
CLIENT_STRICT = 1
CLIENT_AUDIO_BITRATE = '168k'
CLIENT_AUDIO_RATE = 44100
CLIENT_PRESET = 'slow'
CLIENT_HLS_ALLOW_CACHE = 1
CLIENT_HLS_LIST_SIZE = 20
CLIENT_HLS_TIME = 4
CLIENT_FORMAT = 'hls'
CLIENT_FLEX = 1
